apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "supervillain.fullname" . }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "supervillain.cloud"
      secretName: supervillain-cert
  rules:
    - host: "supervillain.cloud"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "supervillain.fullname" . }}
              port: 
                number: {{ .Values.service.port }}
